### ISSUE TITLE
Question about Code Base that you removed BBD stage control 

### ISSUE THREAD

**Issue by aasong113** [MrGavinYu/numerical-solution-of-PDE#1]
Hi, 

I was wondering if I could get the code you wrote for the BBD thorlabs stage control. It was very helpful and we need it to automate a data collection. Please shoot me an email at asong18@jhu.edu when you get a chance. 

Thanks,
Anthony

**Comment by MrGavinYu** [comment]
[Automation-main.zip](https://github.com/user-attachments/files/17331531/Automation-main.zip)

**Comment by aasong113** [comment]
Thank you so muchEl oct 10, 2024, a la(s) 12:45, Gavin Yu ***@***.***> escribió:﻿
Automation-main.zip
